### ISSUE TITLE
GUI: application packaging

### ISSUE THREAD

**Issue by afq984** [afq984/ilmsdump#25]
Ideally, I would like to have it being done on GitHub actions, to avoid human errors.

**Comment by afq984** [comment]
我測了一些 cx_Freeze 跟 pyinstaller 的組合:

| tool+framework \ platform | windows | macOS | Build |
|---|---|---|---|
| cx_Freeze+PySide6 | works, 233MB | build fails | [action](https://github.com/afq984/ilmsdump/actions/runs/438277804) | 
| pyinstaller+PySide6 | PySide6 is not actually bundled, 27MB  | I don't think it will work, 57MB | [action](https://github.com/afq984/ilmsdump/actions/runs/438233631) |
| cx_Freeze+PySide2 | works, 399MB | build fails | [action](https://github.com/afq984/ilmsdump/actions/runs/438401326) |
| pyinstaller+PySide2 | works with [hack], 112MB | 108MB | [action](https://github.com/afq984/ilmsdump/actions/runs/438434321) |

目前看來：
* cx_Freeze 在 mac 上面不會動
* pyinstaller 現在還看不懂 pyside6
* 目前唯一可行的方法是 降到 Qt5 + pyinstaller，
   不過看起來 pyinstaller 會無視 setuptools 存的 metadata，導致[正規方法](https://github.com/afq984/ilmsdump/blob/f737bc032bcb67574e8785e64124e5fe31c928a8/ilmsdump/gui/__init__.py#L60)抓不到檔案
   我自己是不太喜歡 pyinstaller 給的[解決方案](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html)
   要再想其他辦法解決

[hack]: https://github.com/afq984/ilmsdump/blob/e9028b061527a4634837af660d7e1b87d446a311/ilmsdump/gui/hacks.py#L125

@JackKuo-tw  
pyinstaller+PySide2 的配置是可行的嗎？我沒有 mac 沒得測，github action build 好的那包要你幫忙檢查一下。而且我不知道你當初有沒有想要用甚麼功能是 Qt5 沒有的

**Comment by JackKuo-tw** [comment]
@afq984  降到 Qt5 不影響，單純是想說 Qt 6 剛出來所以試試看。
可能你有發現我一開始 PR 的 commit 是 PySide2，也是因為我感覺 Qt6 有些套件不相容才降版測試，但忘己改回去 😅

兩份 buid 在 Mac 上面都無法執行😰

至於你說抓不到檔案是指 `.ui` 嗎？可以用 `pyuic5` 轉成 `.py` 檔 引入試試，不過程式得稍做修改。
這邊有份之前 UI 使用 `.py` 的程式碼供你參考：[pyuic_ilmsdump_example.py](https://gist.github.com/JackKuo-tw/4f0a85bc90a527a80046b64b01c208af)。

BTW，你應該知道但還是提醒一下，Windows 版本要發布時應可以上個 upx 壓縮一下執行檔。

**Comment by JackKuo-tw** [comment]
[`pyinstaller+PySide2`](https://github.com/afq984/ilmsdump/actions/runs/438434321) 我無法在 Windows 10 上面正常執行...

**Comment by afq984** [comment]
> [`pyinstaller+PySide2`](https://github.com/afq984/ilmsdump/actions/runs/438434321) 我無法在 Windows 10 上面正常執行...

可能他會用到我電腦上已經有的 dll
所以我才能跑

@JackKuo-tw 那 cxfreeze 的兩個呢

**Comment by afq984** [comment]
> `pyuic5` 

原來如此，我以前都自己用 code 加 layout XD

> upx

感覺有些防毒軟體不喜歡他

**Comment by JackKuo-tw** [comment]
> 那 cxfreeze 的兩個呢

想說你測試過應該就 ok，沒想到同樣不行 😰，打開來黑畫面
霎時間有股衝動想用 Electron 重寫一個，不過我沒這個閒時間還是算惹

> 原來如此，我以前都自己用 code 加 layout XD

曾經的我也是，直到遇到 Qt Designer XDDDD

> 感覺有些防毒軟體不喜歡他

他們拆殼技術不佳（誤

**Comment by afq984** [comment]
side note: github action artifacts are only available to logged in (github) users
